### ISSUE TITLE
Newest version causes npm dedupe to go nuts

### ISSUE THREAD

**Issue by philkunz** [motss/lit-ntml#56]

**Comment by motss** [comment]
@philkunz Sorry for the cause. There's a new version published at a609b721566d74e1a88b5261c1e43416045d39d3.

I've pulled the version that is causing the problem from NPM.

Thanks for reporting this.

**Comment by philkunz** [comment]
@motss Can you enlighten me about the cause for this? I looked at it as well, but couldn't find the issue causing it...
